name: prayer_tasbeeh
description: "A premium Islamic daily app with prayer times, Tasbeeh, Quran, Duas and Qibla."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Prayer time API
  http: ^1.5.0

  # Date and time formatting
  intl: ^0.20.2

  # Local data storage
  shared_preferences: ^2.5.3

  # GPS location
  geolocator: ^14.0.2

  # Quran / Dua audio
  audioplayers: ^6.5.0

  # Device compass / sensors
  sensors_plus: ^6.1.1

  # Internet connectivity
  connectivity_plus: ^6.1.4

  # Local notifications
  flutter_local_notifications: ^19.4.0

  # Timezone support for notifications
  timezone: ^0.10.1

  # App launcher icon
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
